// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHp3vNoIsvtrjFi2_3ANGgU1Mm85ZaWpk',
    appId: '1:669855856563:web:818738da5160e770d9fdc6',
    messagingSenderId: '669855856563',
    projectId: 'expense-tracker-942fc',
    authDomain: 'expense-tracker-942fc.firebaseapp.com',
    storageBucket: 'expense-tracker-942fc.firebasestorage.app',
    measurementId: 'G-GHETVW7QPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDcB2TA949D7dN25AogDtQ8IzI5UsfqLI',
    appId: '1:669855856563:android:33c5991ab75e6fdbd9fdc6',
    messagingSenderId: '669855856563',
    projectId: 'expense-tracker-942fc',
    storageBucket: 'expense-tracker-942fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpLue6228EmTCtWK0qvXY4312YprxZO1Y',
    appId: '1:669855856563:ios:051a21d445bf4875d9fdc6',
    messagingSenderId: '669855856563',
    projectId: 'expense-tracker-942fc',
    storageBucket: 'expense-tracker-942fc.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpLue6228EmTCtWK0qvXY4312YprxZO1Y',
    appId: '1:669855856563:ios:051a21d445bf4875d9fdc6',
    messagingSenderId: '669855856563',
    projectId: 'expense-tracker-942fc',
    storageBucket: 'expense-tracker-942fc.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHp3vNoIsvtrjFi2_3ANGgU1Mm85ZaWpk',
    appId: '1:669855856563:web:8570ff0017234385d9fdc6',
    messagingSenderId: '669855856563',
    projectId: 'expense-tracker-942fc',
    authDomain: 'expense-tracker-942fc.firebaseapp.com',
    storageBucket: 'expense-tracker-942fc.firebasestorage.app',
    measurementId: 'G-SET0J0NB6Q',
  );
}
